# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class:    SfCmsProject\CmsBundle\Entity\User
                property: username

    encoders:
        #Symfony\Component\Security\Core\User\User: md5
        SfCmsProject\CmsBundle\Entity\User:
            id: sf_cms_project_cms.md5password.encoder
            encode_as_base64: false
            iterations: 0
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/admin
            security: false
        main_login:
                # Cette expression régulière permet de prendre /login (mais pas /login_check !)
            pattern:   ^/login$
            anonymous: true # On autorise alors les anonymes sur ce pare-feu
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     pre_homepage

    access_control:
        - { path: /security/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /cms/admin/security, roles: ROLE_ADMIN }
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
