services:
    sf_cms_project_cms.HomeAndPost:
        class: SfCmsProject\CmsBundle\Services\HomeAndPost

    sf_cms_project_cms.CountSubPage:
        class: SfCmsProject\CmsBundle\Services\CountSubPage
        arguments:
            - "@doctrine.orm.entity_manager"

