<?php

namespace SfCmsProject\CmsBundle\Repository;

/**
 * TemplatePostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplatePostRepository extends \Doctrine\ORM\EntityRepository
{
}
