<?php

namespace SfCmsProject\CmsBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserByRoleAdmin() {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
            ->from('SfCmsProjectCmsBundle:User', 'u')
            ->Where('u.roles LIKE :roles')
            ->setParameter('roles', '%"ROLE_ADMIN"%' );

        return $qb->getQuery()->getResult();
    }
}
